In [36]:
import pandas as pd

In [37]:
import numpy as np

Detail :
rainfall_category = 
1 = ringan
2 = sedang
3 = lebat

In [38]:
data = pd.read_csv("data_set/ds_21.csv")
data

Tahun  Bulan   tgl temp7 temp13 temp18 temp_avg temp_24 temp_max  \
0     2021      1   1.0  26.3   32.3   28.8     28.4    28.4     32.9   
1     2021      1   2.0  26.1   31.5   27.2     27.7    27.5     31.7   
2     2021      1   3.0  26.6   31.4   26.6     27.8    27.8     32.5   
3     2021      1   4.0  26.2   31.8   29.5     28.4    28.6     33.0   
4     2021      1   5.0  27.2   26.8   26.6     27.0    27.0     32.4   
..     ...    ...   ...   ...    ...    ...      ...     ...      ...   
361   2021     12  27.0  27.9   34.7   25.9     29.1    27.2     35.7   
362   2021     12  28.0  26.4   33.6   27.4     28.5    27.7     35.8   
363   2021     12  29.0  26.3   32.7   30.4     28.9    29.0     34.0   
364   2021     12  30.0  27.0   32.2   25.4     27.9    27.8     33.4   
365   2021     12  31.0  26.3   33.0   25.2     27.7    27.5     33.8   

    temp_min  ...             humid7             humid13            humid18  \
0       24.6  ...  92.72339050173582    65.0188026263269   79.9792315683067   
1       25.2  ...  69.40288984888305   86.71938446937911               84.0   
2       25.6  ...   86.5437471238459   69.97066069376442  90.41467422295305   
3       25.5  ...   86.4234912104948   62.88699987233136  74.78721885027767   
4       25.4  ...  92.08725069158208   90.45670689176886  88.85779948974681   
..       ...  ...                ...                 ...                ...   
361     24.6  ...  80.31654583977061  56.576342055224984  91.05908580220675   
362     25.1  ...  88.80836197722951   62.96448376775169  77.92790980700342   
363     26.0  ...   91.9296224982397  59.465948515600964  74.57811767655987   
364     24.0  ...  85.90249604768772   64.95270684844482  90.15280438641373   
365     24.6  ...  92.72339050173582    63.1343532920419   94.9996701525737   

    humid_avg humid_24              ws_abg mod_dir max_ws    dir  \
0        83.0     82.0                3.25       B    6.0  190.0   
1        86.0    3.125                  TG     7.0   50.0  180.0   
2        83.0     83.0  3.9583333333333335      BL   10.0  160.0   
3        78.0     78.0               3.375      BL    7.0  330.0   
4        91.0     88.0  3.5833333333333335       B   16.0  310.0   
..        ...      ...                 ...     ...    ...    ...   
361      77.0     84.0   6.083333333333333       B   21.0  140.0   
362      80.0     82.0   4.291666666666667       B   17.0  160.0   
363      79.0     80.0                 5.0      BL   12.0  330.0   
364      82.0     84.0                4.75      BL   13.0  320.0   
365      86.0     86.0  3.4583333333333335      TG   10.0  330.0   

    rainfall_category  
0                 1.0  
1                 2.0  
2                 3.0  
3                 NaN  
4                 NaN  
..                ...  
361               NaN  
362               NaN  
363               NaN  
364               NaN  
365               NaN  

[366 rows x 26 columns]

In [39]:
print(data.isna().sum())

Tahun                  0
Bulan                  0
tgl                    0
temp7                  0
temp13                 0
temp18                 0
temp_avg               0
temp_24                0
temp_max               0
temp_min               0
CH                     0
light_hour             0
light_per              0
pck                    0
tgl.1                  0
press                  0
humid7                 0
humid13                0
humid18                0
humid_avg              0
humid_24               0
ws_abg                 0
mod_dir                0
max_ws                 0
dir                    0
rainfall_category    363
dtype: int64


In [40]:
data.count()

Tahun                366
Bulan                366
tgl                  366
temp7                366
temp13               366
temp18               366
temp_avg             366
temp_24              366
temp_max             366
temp_min             366
CH                   366
light_hour           366
light_per            366
pck                  366
tgl.1                366
press                366
humid7               366
humid13              366
humid18              366
humid_avg            366
humid_24             366
ws_abg               366
mod_dir              366
max_ws               366
dir                  366
rainfall_category      3
dtype: int64

In [41]:
data

Tahun  Bulan   tgl temp7 temp13 temp18 temp_avg temp_24 temp_max  \
0     2021      1   1.0  26.3   32.3   28.8     28.4    28.4     32.9   
1     2021      1   2.0  26.1   31.5   27.2     27.7    27.5     31.7   
2     2021      1   3.0  26.6   31.4   26.6     27.8    27.8     32.5   
3     2021      1   4.0  26.2   31.8   29.5     28.4    28.6     33.0   
4     2021      1   5.0  27.2   26.8   26.6     27.0    27.0     32.4   
..     ...    ...   ...   ...    ...    ...      ...     ...      ...   
361   2021     12  27.0  27.9   34.7   25.9     29.1    27.2     35.7   
362   2021     12  28.0  26.4   33.6   27.4     28.5    27.7     35.8   
363   2021     12  29.0  26.3   32.7   30.4     28.9    29.0     34.0   
364   2021     12  30.0  27.0   32.2   25.4     27.9    27.8     33.4   
365   2021     12  31.0  26.3   33.0   25.2     27.7    27.5     33.8   

    temp_min  ...             humid7             humid13            humid18  \
0       24.6  ...  92.72339050173582    65.0188026263269   79.9792315683067   
1       25.2  ...  69.40288984888305   86.71938446937911               84.0   
2       25.6  ...   86.5437471238459   69.97066069376442  90.41467422295305   
3       25.5  ...   86.4234912104948   62.88699987233136  74.78721885027767   
4       25.4  ...  92.08725069158208   90.45670689176886  88.85779948974681   
..       ...  ...                ...                 ...                ...   
361     24.6  ...  80.31654583977061  56.576342055224984  91.05908580220675   
362     25.1  ...  88.80836197722951   62.96448376775169  77.92790980700342   
363     26.0  ...   91.9296224982397  59.465948515600964  74.57811767655987   
364     24.0  ...  85.90249604768772   64.95270684844482  90.15280438641373   
365     24.6  ...  92.72339050173582    63.1343532920419   94.9996701525737   

    humid_avg humid_24              ws_abg mod_dir max_ws    dir  \
0        83.0     82.0                3.25       B    6.0  190.0   
1        86.0    3.125                  TG     7.0   50.0  180.0   
2        83.0     83.0  3.9583333333333335      BL   10.0  160.0   
3        78.0     78.0               3.375      BL    7.0  330.0   
4        91.0     88.0  3.5833333333333335       B   16.0  310.0   
..        ...      ...                 ...     ...    ...    ...   
361      77.0     84.0   6.083333333333333       B   21.0  140.0   
362      80.0     82.0   4.291666666666667       B   17.0  160.0   
363      79.0     80.0                 5.0      BL   12.0  330.0   
364      82.0     84.0                4.75      BL   13.0  320.0   
365      86.0     86.0  3.4583333333333335      TG   10.0  330.0   

    rainfall_category  
0                 1.0  
1                 2.0  
2                 3.0  
3                 NaN  
4                 NaN  
..                ...  
361               NaN  
362               NaN  
363               NaN  
364               NaN  
365               NaN  

[366 rows x 26 columns]

In [42]:
data = data.drop(columns=['Tahun', 'temp7', 'temp13', 'temp18', 'temp_24', 'temp_max', 'temp_min', 'humid7', 'humid13', 'humid18', 'humid_24', 'ws_abg', 'mod_dir', 'max_ws', 'dir', 'CH', 'light_hour', 'light_per', 'pck', 'press'], axis=1)
data

Bulan   tgl temp_avg   tgl.1 humid_avg  rainfall_category
0        1   1.0     28.4     1.0      83.0                1.0
1        1   2.0     27.7  1009.3      86.0                2.0
2        1   3.0     27.8     3.0      83.0                3.0
3        1   4.0     28.4     4.0      78.0                NaN
4        1   5.0     27.0     5.0      91.0                NaN
..     ...   ...      ...     ...       ...                ...
361     12  27.0     29.1    27.0      77.0                NaN
362     12  28.0     28.5    28.0      80.0                NaN
363     12  29.0     28.9    29.0      79.0                NaN
364     12  30.0     27.9    30.0      82.0                NaN
365     12  31.0     27.7    31.0      86.0                NaN

[366 rows x 6 columns]

In [43]:
data

Bulan   tgl temp_avg   tgl.1 humid_avg  rainfall_category
0        1   1.0     28.4     1.0      83.0                1.0
1        1   2.0     27.7  1009.3      86.0                2.0
2        1   3.0     27.8     3.0      83.0                3.0
3        1   4.0     28.4     4.0      78.0                NaN
4        1   5.0     27.0     5.0      91.0                NaN
..     ...   ...      ...     ...       ...                ...
361     12  27.0     29.1    27.0      77.0                NaN
362     12  28.0     28.5    28.0      80.0                NaN
363     12  29.0     28.9    29.0      79.0                NaN
364     12  30.0     27.9    30.0      82.0                NaN
365     12  31.0     27.7    31.0      86.0                NaN

[366 rows x 6 columns]

In [44]:
data['rainfall_category'] = data['rainfall_category'].fillna(0)

In [45]:
data

Bulan   tgl temp_avg   tgl.1 humid_avg  rainfall_category
0        1   1.0     28.4     1.0      83.0                1.0
1        1   2.0     27.7  1009.3      86.0                2.0
2        1   3.0     27.8     3.0      83.0                3.0
3        1   4.0     28.4     4.0      78.0                0.0
4        1   5.0     27.0     5.0      91.0                0.0
..     ...   ...      ...     ...       ...                ...
361     12  27.0     29.1    27.0      77.0                0.0
362     12  28.0     28.5    28.0      80.0                0.0
363     12  29.0     28.9    29.0      79.0                0.0
364     12  30.0     27.9    30.0      82.0                0.0
365     12  31.0     27.7    31.0      86.0                0.0

[366 rows x 6 columns]

In [46]:
numeric_column = ['temp_avg', 'humid_avg', 'rainfall_category']

for columns in numeric_column:
    data[columns] = pd.to_numeric(data[columns], errors='coerce')

In [47]:
data

Bulan   tgl  temp_avg   tgl.1  humid_avg  rainfall_category
0        1   1.0      28.4     1.0       83.0                1.0
1        1   2.0      27.7  1009.3       86.0                2.0
2        1   3.0      27.8     3.0       83.0                3.0
3        1   4.0      28.4     4.0       78.0                0.0
4        1   5.0      27.0     5.0       91.0                0.0
..     ...   ...       ...     ...        ...                ...
361     12  27.0      29.1    27.0       77.0                0.0
362     12  28.0      28.5    28.0       80.0                0.0
363     12  29.0      28.9    29.0       79.0                0.0
364     12  30.0      27.9    30.0       82.0                0.0
365     12  31.0      27.7    31.0       86.0                0.0

[366 rows x 6 columns]

In [48]:
data = data.dropna()
data

Bulan   tgl  temp_avg   tgl.1  humid_avg  rainfall_category
0        1   1.0      28.4     1.0       83.0                1.0
1        1   2.0      27.7  1009.3       86.0                2.0
2        1   3.0      27.8     3.0       83.0                3.0
3        1   4.0      28.4     4.0       78.0                0.0
4        1   5.0      27.0     5.0       91.0                0.0
..     ...   ...       ...     ...        ...                ...
361     12  27.0      29.1    27.0       77.0                0.0
362     12  28.0      28.5    28.0       80.0                0.0
363     12  29.0      28.9    29.0       79.0                0.0
364     12  30.0      27.9    30.0       82.0                0.0
365     12  31.0      27.7    31.0       86.0                0.0

[365 rows x 6 columns]

In [49]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

data[['temp', 'humidity']] = scaler.fit_transform(data[['temp_avg', 'humid_avg']])

/var/folders/l8/wksw6z8d6p1g8jf93wktmwgc0000gn/T/ipykernel_1279/3169961385.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['temp', 'humidity']] = scaler.fit_transform(data[['temp_avg', 'humid_avg']])
/var/folders/l8/wksw6z8d6p1g8jf93wktmwgc0000gn/T/ipykernel_1279/3169961385.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['temp', 'humidity']] = scaler.fit_transform(data[['temp_avg', 'humid_avg']])


In [50]:
def create_sequences(data, n_steps):
    X, y = [], []
    for i in range(len(data) - n_steps):
        X.append(data.iloc[i:i+n_steps, :-1].values)
        y.append(data.iloc[i+n_steps, -1])
    return np.array(X), np.array(y)

n_steps = 7
X, y = create_sequences(data, n_steps)

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [52]:
print(f"Shape X_train: {X_train.shape}, y_train: {y_train.shape}")

Shape X_train: (286, 7, 7), y_train: (286,)


In [53]:
import numpy as np
from tensorflow.keras.utils import to_categorical

# Contoh data y_test
y_test = np.array([0, 1, 2, np.nan, 3, -1])  # Data dengan nilai yang bermasalah

# Tangani nilai NaN
y_test = np.nan_to_num(y_test, nan=0)

# Konversi ke integer
y_test = y_test.astype(int)

# Validasi rentang nilai
num_classes = 3
y_test = np.clip(y_test, 0, num_classes-1)

# Konversi ke kategori
y_test_categorical = to_categorical(y_test, num_classes=num_classes)

print("y_test_categorical:", y_test_categorical)


y_test_categorical: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [54]:
from tensorflow.keras.utils import to_categorical

y_train = to_categorical(y_train, num_classes=3)
y_test = to_categorical(y_test, num_classes=3)

In [55]:
print(y_train.dtype)

float64


In [56]:
print(f"X_train shape: {X_train.shape}, dtype: {X_train.dtype}")
print(f"y_train shape: {y_train.shape}, dtype: {y_train.dtype}")
print(f"X_test shape: {X_test.shape}, dtype: {X_test.dtype}")
print(f"y_test shape: {y_test.shape}, dtype: {y_test.dtype}")


X_train shape: (286, 7, 7), dtype: object
y_train shape: (286, 3), dtype: float64
X_test shape: (72, 7, 7), dtype: object
y_test shape: (6, 3), dtype: float64


In [57]:
# Ganti string kosong (' ') dengan NaN, lalu isi NaN dengan nilai tertentu (misal 0)
X_train = np.where(X_train == ' ', np.nan, X_train)
X_train = np.where(X_train == '', np.nan, X_train)

# Konversi ke float, isi NaN dengan 0
X_train = np.array(X_train, dtype=np.float32)
X_train = np.nan_to_num(X_train)


In [58]:
print(X_train.dtype)  # Harus berupa float32
print(np.isnan(X_train).any())  # Pastikan tidak ada NaN
print(X_train.shape)  # Pastikan bentuknya sesuai (samples, time_steps, features)


float32
False
(286, 7, 7)


In [59]:
# Ganti string kosong (' ') dengan NaN, lalu isi NaN dengan nilai tertentu (misal 0)
X_test = np.where(X_test == ' ', np.nan, X_test)
X_test = np.where(X_test == '', np.nan, X_test)

# Konversi ke float, isi NaN dengan 0
X_test = np.array(X_test, dtype=np.float32)
X_test = np.nan_to_num(X_test)

In [60]:
print(X_test.dtype)  # Harus berupa float32
print(np.isnan(X_test).any())  # Pastikan tidak ada NaN
print(X_test.shape)  # Pastikan bentuknya sesuai (samples, time_steps, features)


float32
False
(72, 7, 7)


In [61]:
import numpy as np

X_train = np.array(X_train, dtype=np.float32)
X_test = np.array(X_test, dtype=np.float32)

In [62]:
min_samples = min(len(X_train), len(y_train))

X_train = X_train[:min_samples]
y_train = y_train[:min_samples]

print("Sinkronisasi selesai!")
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)


Sinkronisasi selesai!
X_train shape: (286, 7, 7)
y_train shape: (286, 3)


In [63]:
from sklearn.model_selection import train_test_split

# Pastikan pembagian data dilakukan dengan benar
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Pembagian data selesai!")
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)


Pembagian data selesai!
X_train shape: (286, 7, 7)
y_train shape: (286,)


In [64]:
import numpy as np

print("Unique values in y_test:", np.unique(y_test))


Unique values in y_test: [0.27777778 0.30555556 0.33333333 0.38888889 0.41666667 0.44444444
 0.47222222 0.5        0.52777778 0.55555556 0.58333333 0.61111111
 0.63888889 0.66666667 0.69444444 0.72222222 0.75       0.77777778
 0.80555556 0.83333333 0.86111111]


In [65]:
valid_classes = [0, 1, 2]
y_test = np.array([y for y in y_test if y in valid_classes])


In [66]:
y_test = y_test.astype(int)


In [67]:
num_classes = len(np.unique(y_test))
print("Number of classes:", num_classes)


Number of classes: 0


In [68]:
print("y_test shape:", y_test.shape)
print("y_test values:", y_test[:10])  # Cek 10 nilai pertama


y_test shape: (0,)
y_test values: []


In [69]:
from tensorflow.keras.utils import to_categorical

# Konversi ke one-hot encoding
y_train = to_categorical(y_train, num_classes=3)
y_test = to_categorical(y_test, num_classes=3)


In [70]:
import numpy as np

print("X_train contains NaN:", np.isnan(X_train).any())
print("X_test contains NaN:", np.isnan(X_test).any())
print("y_train contains NaN:", np.isnan(y_train).any())
print("y_test contains NaN:", np.isnan(y_test).any())


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.optimizers import Adam

model = Sequential()
model.add(LSTM(64, input_shape=(X_train.shape[1], X_train.shape[2]), return_sequences = False))
model.add(Dense(32, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))


ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type int).